namespace: kube-system
helmCharts:
  - name: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    chart: metrics-server
    version: 3.12.2
    namespace: kube-system

  - name: reloader
    repoURL: https://stakater.github.io/stakater-charts
    chart: stakater/reloader
    version: 1.1.0
    namespace: kube-system
