apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-ap-southeast-2-development
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/chamarakera/argocd-deployment-patterns.git'
        revision: main
        files:
        - path: "pattern-1/configs/development/ap-southeast-2.yaml"
  template:
    metadata:
      name: '{{ helmCharts.name }}'
    spec:
      project: default
      # Source of the application manifests
      source:
        repoURL: '{{ helmCharts.repoURL }}'
        targetRevision: '{{ helmCharts.version }}'
      
        # helm specific config
        chart: '{{ helmCharts.chart }}'
        helm:
          releaseName: '{{ helmCharts.name }}'

      destination:
        server: 'https://kubernetes.default.svc'
        # server: 'ap-southeast-2-development'
        namespace: '{{ namespace }}'
