apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: system-ap-southeast-2
 namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/chamarakera/argocd-deployment-patterns.git'
        revision: main
        files:
        - path: "pattern-1/configs/development/ap-southeast-2.json"
  template:
    metadata:
      name: '{{ addon.name }}'
    spec:
      project: default
      # Source of the application manifests
      source:
        repoURL: '{{ addon.repoURL }}'
        targetRevision: '{{ addon.gitBranch }}'
      
        # helm specific config
        chart: '{{ addon.chart }}'
        helm:
          releaseName: '{{ addon.name }}'

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ addon.namespace }}'
